### ISSUE TITLE
Redirect manifest link

### ISSUE THREAD

**Issue by pgsocks** [crekulon/tspy#7]
Since the launcher manifest link is hosted on the root domain, the link to the manifest needs to redirect to the location of the manifest. This can be accomplished by putting the whole site behind Nginx, but a purely Jekyll solution for redirecting that one link would be preferable.

**Comment by crekulon** [comment]
talked about this on discord, but for posterity: Jekyll is purely static, so any redirect will be JS-based and not actually affect HTTP requests from launchers and other such stuff. Nginx or a proxy service will be the way to go for a real 301 redirect

**Comment by pgsocks** [comment]
Done with a Nginx reverse proxy.
